<?php
/**
 * @file epract_include_php.module
 */

/**
 * hook_menu.
 */
function epract_include_php_menu() {
  $items = array();
  $items['epract/include/php'] = array(
    'title'            => 'Php page',
    'title callback' => 'epract_include_php_title_callback',
    'description'      => 'Include custom php in a page',
    'page callback'    => 'epract_include_php_prueba',
    'type'             => MENU_CALLBACK,
    'access callback' => 'user_is_logged_in',
  );
  return $items;
}
function epract_include_php_title_callback($title) {
  $parametros = drupal_get_query_parameters();    
  $title=t($parametros['idG']);
  //dpm($title);
  return $title;
}


function epract_include_php_prueba() {
  $parametros = drupal_get_query_parameters();
  global $user;
  global $node;
  //dpm($node);
  if ($parametros['idG']==1) {
    exec('Rscript /var/www/e-pract.net/web/empodera/scriptsR/pruebaCR.R');
    if (file_exists('/var/www/e-pract.net/web/empodera/scriptsR/prueba1.png')) {
      $image = theme_image(array(path => 'http://dev.epract.net/empodera/scriptsR/prueba1.png?'.time()));
      return '<h3>Titulo</h3>'.$image;
    }
  }
  //return('Not graphic found');
  drupal_goto('<front>');
}

function epract_include_php_block_info() {
  // This example comes from node.module.
  $blocks['ver_resultados'] = array(
    'info' => t('Ver resultados'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function epract_include_php_block_view($delta = '') {
  // This example is adapted from node.module.
  //dpm(arg(0).'/'.arg(1).'/'.arg(2).'/'.arg(3).'/'.arg(4));
  if (arg(4)=='view') {
  $block = array();
  switch ($delta) {
    case 'ver_resultados':
      global $node;
      $block['subject'] = t('Ver resultados');
      exec('Rscript /var/www/e-pract.net/web/empodera/scriptsR/pruebaCR.R');
      if (file_exists('/var/www/e-pract.net/web/empodera/scriptsR/prueba1.png')) {
        $image = theme_image(array(path => 'http://dev.epract.net/empodera/scriptsR/prueba1.png?'.time()));
        $block['content'] = array(
          '#markup' => '<div style="width: 100%; text-align: center">'.$image.'</div>',
      );
      }
      //       = array(
        //'#theme' => 'feed_icon', 
        //'#url' => 'rss.xml', 
        //'#title' => t('Syndicate'),
      //);
      break;
  }
  return $block;
  }
}
